#ifndef LEXER_H
#define LEXER_H

#include "token.h"
#include "transition_table.h"

/**
 * Lexer structure representing a lexical analyzer.
 *
 * Members:
 * - tokens: Pointer to a TokenList containing the tokens generated by the
 * lexer.
 * - source_code: Pointer to the source code string to be lexed.
 * - position: Current position in the source code.
 * - symbol_table_file: File pointer for writing the symbol table.
 *
 * symbol_table_file is used to output the symbol table to a file named
 * "symbol_table.txt".
 */
struct Lexer {
        struct TokenList *tokens;
        char *source_code;
        size_t position;

        FILE *symbol_table_file;
};

/**
 * Initializes a Lexer structure with the given source code.
 */
void lexer_init(struct Lexer *lexer, char *source);

/**
 * Performs lexical analysis on the source code and populates the token list.
 */
void lexer_lex(struct Lexer *lexer);

/**
 * Prints the tokens in the lexer's token list to the symbol table file.
 */
void lexer_print_toks(struct Lexer *lx);

#endif